=== AlJungOrg/JVP-Modbus/jsonschema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "Addresses": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "Active": { "type": "boolean" },
          "ByteOrder": { "type": "integer", "minimum": -1, "maximum": 3 },
          "DataType": { "type": "integer", "minimum": -1, "maximum": 14 },
          "Factor": { "type": "number" },
          "Name": { "type": "string" },
          "Description": { "type": "string" },
          "Profile": { "type": "string" },
          "ReadAddress": { "type": "integer" },
          "ReadFunctionCode": { "type": "integer", "enum": [0, 1, 2, 3, 4, 6, 15, 16] },
          "WriteAddress": { "type": "integer" },
          "WriteFunctionCode": { "type": "integer", "enum": [0, 1, 2, 3, 4, 6, 15, 16] },
          "Translation": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "Language": { "type": "string" },
                "Name": { "type": "string" }
              },
              "required": ["Language", "Name"]
            }
          },
          "Interval": { "type": "integer" }
        },
        "required": [
          "Active", "DataType", "Factor", 
          "Profile", "ReadAddress", "ReadFunctionCode", "WriteAddress",
          "WriteFunctionCode", "Translation"
        ]
      }
    },
    "ByteOrder": { "type": "integer", "minimum": -1, "maximum": 3 },
    "ByteOrderFloats": { "type": "boolean" },
    "Active": { "type": "boolean" },
    "ReferenceCountStartsAtZero": { "type": "boolean" },
    "UseEnronMode": { "type": "boolean" },
    "Name": { "type": "string" },
    "Description": { "type": "string" },
    "ConnectionType": { "type": "string", "enum": ["TCP", "RTU"] },
    "Profiles": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "Associations": { "type": "array", "items": {} },
          "Digits": { "type": "integer" },
          "Icon": { "type": "string" },
          "MaxValue": { "type": "number" },
          "MinValue": { "type": "number" },
          "Prefix": { "type": "string" },
          "StepSize": { "type": "number" },
          "Suffix": { "type": "string" },
          "Type": { "type": "integer" }
        },
        "required": [
          "Associations", "Digits", "Icon", "MaxValue", "MinValue", "Prefix",
          "StepSize", "Suffix", "Type"
        ]
      }
    },
    "Requests": {
      "type": "object",
      "properties": {
        "Interval": { "type": "integer" }
      },
      "required": ["Interval"]
    },
    "Type": { "type": "string" },
    "Manufacturer": { "type": "string" },
    "Product": { "type": "string" }
  },
  "required": [
    "Addresses", "ByteOrder", "Profiles", "Requests"
  ]
}

=== AlJungOrg/JVP-Modbus/product_catalog/energy_meter/EASTRON/SDM630/product.json
{
    "Addresses": [
        {
            "Active": true,
            "ByteOrder": -1,
            "DataType": 7,
            "Factor": 1,
            "Name": "Voltage L1",
            "Description": "",
            "Profile": "",
            "ReadAddress": 1,
            "ReadFunctionCode": 4,
            "WriteAddress": 1,
            "WriteFunctionCode": 0,
            "Translation": [
                {
                    "Language": "de",
                    "Name": ""
                },
                {
                    "Language": "en",
                    "Name": ""
                }
            ],
            "Interval": 6000
        },
        {
            "Active": true,
            "ByteOrder": -1,
            "DataType": 7,
            "Factor": 1,
            "Name": "Frequenzy",
            "Description": "",
            "Profile": "",
            "ReadAddress": 71,
            "ReadFunctionCode": 4,
            "WriteAddress": 71,
            "WriteFunctionCode": 0,
            "Translation": [
                {
                    "Language": "de",
                    "Name": ""
                },
                {
                    "Language": "en",
                    "Name": ""
                }
            ],
            "Interval": 6000
        },
        {
            "Active": true,
            "ByteOrder": -1,
            "DataType": 7,
            "Factor": 1,
            "Name": "active Power",
            "Description": "",
            "Profile": "",
            "ReadAddress": 73,
            "ReadFunctionCode": 4,
            "WriteAddress": 73,
            "WriteFunctionCode": 0,
            "Translation": [
                {
                    "Language": "de",
                    "Name": ""
                },
                {
                    "Language": "en",
                    "Name": ""
                }
            ],
            "Interval": 6000
        }
    ],
    "ByteOrder": 0,
    "ByteOrderFloats": true,
    "Active": true,
    "ReferenceCountStartsAtZero": false,
    "UseEnronMode": false,
    "Name": "SDM630",
    "Description": "",
    "ConnectionType": "TCP",
    "Profiles": {},
    "Requests": {
        "Interval": 6000
    },
    "Type": "Energy_Meter"
}

=== AlJungOrg/JVP-Modbus/product_catalog/energy_meter/Socomec/E2X/product.json
{
    "Addresses": [
        {
            "Active": true,
            "ByteOrder": -1,
            "DataType": 3,
            "Factor": 1,
            "Name": "Simple voltage : V1",
            "Description": "Simple voltage : V1",
            "Profile": "",
            "ReadAddress": 50520,
            "ReadFunctionCode": 3,
            "WriteAddress": 50520,
            "WriteFunctionCode": 0,
            "Translation": [
                {
                    "Language": "de",
                    "Name": ""
                },
                {
                    "Language": "en",
                    "Name": ""
                }
            ],
            "Interval": 6000
        },
        {
            "Active": true,
            "ByteOrder": -1,
            "DataType": 6,
            "Factor": 1,
            "Name": "Sum Active Power +/- : P",
            "Description": "Sum Active Power +/- : P",
            "Profile": "",
            "ReadAddress": 50536,
            "ReadFunctionCode": 3,
            "WriteAddress": 50536,
            "WriteFunctionCode": 0,
            "Translation": [
                {
                    "Language": "de",
                    "Name": ""
                },
                {
                    "Language": "en",
                    "Name": ""
                }
            ],
            "Interval": 6000
        },
        {
            "Active": true,
            "ByteOrder": -1,
            "DataType": 3,
            "Factor": 1,
            "Name": "\tTotal Positive Active Energy (no resetable) : Ea+",
            "Description": "\tTotal Positive Active Energy (no resetable) : Ea+",
            "Profile": "",
            "ReadAddress": 50946,
            "ReadFunctionCode": 3,
            "WriteAddress": 50946,
            "WriteFunctionCode": 0,
            "Translation": [
                {
                    "Language": "de",
                    "Name": ""
                },
                {
                    "Language": "en",
                    "Name": ""
                }
            ],
            "Interval": 6000
        },
        {
            "Active": true,
            "ByteOrder": -1,
            "DataType": 3,
            "Factor": 1,
            "Name": "Total Positive Reactive Energy (no resetable) : Er +",
            "Description": "Total Positive Reactive Energy (no resetable) : Er +",
            "Profile": "",
            "ReadAddress": 50948,
            "ReadFunctionCode": 3,
            "WriteAddress": 50948,
            "WriteFunctionCode": 0,
            "Translation": [
                {
                    "Language": "de",
                    "Name": ""
                },
                {
                    "Language": "en",
                    "Name": ""
                }
            ],
            "Interval": 6000
        },
        {
            "Active": true,
            "ByteOrder": -1,
            "DataType": 3,
            "Factor": 1,
            "Name": "Total Apparent Energy (no resetable) : Eap",
            "Description": "Total Apparent Energy (no resetable) : Eap",
            "Profile": "",
            "ReadAddress": 50950,
            "ReadFunctionCode": 3,
            "WriteAddress": 50950,
            "WriteFunctionCode": 0,
            "Translation": [
                {
                    "Language": "de",
                    "Name": ""
                },
                {
                    "Language": "en",
                    "Name": ""
                }
            ],
            "Interval": 6000
        },
        {
            "Active": true,
            "ByteOrder": -1,
            "DataType": 3,
            "Factor": 1,
            "Name": "Partial Positive Active Energy: Ea+",
            "Description": "Partial Positive Active Energy: Ea+",
            "Profile": "",
            "ReadAddress": 50956,
            "ReadFunctionCode": 3,
            "WriteAddress": 50956,
            "WriteFunctionCode": 0,
            "Translation": [
                {
                    "Language": "de",
                    "Name": ""
                },
                {
                    "Language": "en",
                    "Name": ""
                }
            ],
            "Interval": 5000
        },
        {
            "Active": true,
            "ByteOrder": -1,
            "DataType": 3,
            "Factor": 1,
            "Name": "Partial Apparent Energy : Eap",
            "Description": "Partial Apparent Energy : Eap",
            "Profile": "",
            "ReadAddress": 50960,
            "ReadFunctionCode": 3,
            "WriteAddress": 50960,
            "WriteFunctionCode": 0,
            "Translation": [
                {
                    "Language": "de",
                    "Name": ""
                },
                {
                    "Language": "en",
                    "Name": ""
                }
            ],
            "Interval": 6000
        },
        {
            "Active": true,
            "ByteOrder": -1,
            "DataType": 3,
            "Factor": 1,
            "Name": "Partial Negative Reactive Energy : Er -",
            "Description": "Partial Negative Reactive Energy : Er -",
            "Profile": "",
            "ReadAddress": 50964,
            "ReadFunctionCode": 3,
            "WriteAddress": 50964,
            "WriteFunctionCode": 0,
            "Translation": [
                {
                    "Language": "de",
                    "Name": ""
                },
                {
                    "Language": "en",
                    "Name": ""
                }
            ],
            "Interval": 6000
        },
        {
            "Active": true,
            "ByteOrder": -1,
            "DataType": 2,
            "Factor": 1,
            "Name": "Socomec_Reset Partielle  Zählerwerte",
            "Description": "Socomec_Reset Partielle  Zählerwerte",
            "Profile": "",
            "ReadAddress": 57890,
            "ReadFunctionCode": 0,
            "WriteAddress": 57890,
            "WriteFunctionCode": 16,
            "Translation": [
                {
                    "Language": "de",
                    "Name": ""
                },
                {
                    "Language": "en",
                    "Name": ""
                }
            ],
            "Interval": 6000
        }
    ],
    "ByteOrder": 0,
    "ByteOrderFloats": true,
    "Active": true,
    "ReferenceCountStartsAtZero": true,
    "UseEnronMode": false,
    "Name": "Countis E28",
    "Description": "",
    "ConnectionType": "TCP",
    "Profiles": {},
    "Requests": {
        "Interval": 6000
    },
    "Type": "Energy_Meter"
}

=== AlJungOrg/JVP-Modbus/product_catalog/energy_meter/B+G e-tech GmbH/WS100/product.json
{
    "Addresses": [
        {
            "Active": true,
            "ByteOrder": -1,
            "DataType": 6,
            "Factor": 0.001,
            "Name": "Voltage",
            "Description": "Voltage",
            "Profile": "",
            "ReadAddress": 256,
            "ReadFunctionCode": 3,
            "WriteAddress": 256,
            "WriteFunctionCode": 0,
            "Translation": [
                {
                    "Language": "de",
                    "Name": "Spannung"
                },
                {
                    "Language": "en",
                    "Name": "Voltage"
                }
            ],
            "Interval": 6000
        },
        {
            "Active": true,
            "ByteOrder": -1,
            "DataType": 6,
            "Factor": 0.01,
            "Name": "Current",
            "Description": "Current",
            "Profile": "",
            "ReadAddress": 258,
            "ReadFunctionCode": 3,
            "WriteAddress": 258,
            "WriteFunctionCode": 0,
            "Translation": [
                {
                    "Language": "de",
                    "Name": "Strom"
                },
                {
                    "Language": "en",
                    "Name": "Current"
                }
            ],
            "Interval": 6000
        },
        {
            "Active": true,
            "ByteOrder": -1,
            "DataType": 6,
            "Factor": 1,
            "Name": "Active Power",
            "Description": "Active Power",
            "Profile": "",
            "ReadAddress": 260,
            "ReadFunctionCode": 3,
            "WriteAddress": 260,
            "WriteFunctionCode": 0,
            "Translation": [
                {
                    "Language": "de",
                    "Name": "Wirkleistung"
                },
                {
                    "Language": "en",
                    "Name": "Active Power"
                }
            ],
            "Interval": 6000
        },
        {
            "Active": true,
            "ByteOrder": -1,
            "DataType": 6,
            "Factor": 1,
            "Name": "Apparent Power",
            "Description": "Apparent Power",
            "Profile": "",
            "ReadAddress": 262,
            "ReadFunctionCode": 3,
            "WriteAddress": 262,
            "WriteFunctionCode": 0,
            "Translation": [
                {
                    "Language": "de",
                    "Name": "Scheinleistung"
                },
                {
                    "Language": "en",
                    "Name": "Apparent Power"
                }
            ],
            "Interval": 6000
        },
        {
            "Active": true,
            "ByteOrder": -1,
            "DataType": 6,
            "Factor": 1,
            "Name": "Reactive Power",
            "Description": "Reactive Power",
            "Profile": "",
            "ReadAddress": 264,
            "ReadFunctionCode": 3,
            "WriteAddress": 264,
            "WriteFunctionCode": 0,
            "Translation": [
                {
                    "Language": "de",
                    "Name": "Blindleistung"
                },
                {
                    "Language": "en",
                    "Name": "Reactive Power"
                }
            ],
            "Interval": 6000
        },
        {
            "Active": true,
            "ByteOrder": -1,
            "DataType": 5,
            "Factor": 0.1,
            "Name": "Frequency",
            "Description": "Frequency",
            "Profile": "",
            "ReadAddress": 266,
            "ReadFunctionCode": 3,
            "WriteAddress": 266,
            "WriteFunctionCode": 0,
            "Translation": [
                {
                    "Language": "de",
                    "Name": "Frequenz"
                },
                {
                    "Language": "en",
                    "Name": "Frequency"
                }
            ],
            "Interval": 6000
        },
        {
            "Active": true,
            "ByteOrder": -1,
            "DataType": 5,
            "Factor": 0.001,
            "Name": "Power Factor",
            "Description": "Power Factor",
            "Profile": "",
            "ReadAddress": 267,
            "ReadFunctionCode": 3,
            "WriteAddress": 267,
            "WriteFunctionCode": 0,
            "Translation": [
                {
                    "Language": "de",
                    "Name": "Leistungsfaktor"
                },
                {
                    "Language": "en",
                    "Name": "Power Factor"
                }
            ],
            "Interval": 6000
        },
        {
            "Active": true,
            "ByteOrder": -1,
            "DataType": 6,
            "Factor": 0.01,
            "Name": "Total forward active energy",
            "Description": "Total forward active energy",
            "Profile": "",
            "ReadAddress": 270,
            "ReadFunctionCode": 3,
            "WriteAddress": 270,
            "WriteFunctionCode": 0,
            "Translation": [
                {
                    "Language": "de",
                    "Name": "Gesamt Wirkarbeit Bezug"
                },
                {
                    "Language": "en",
                    "Name": "Total forward active energy"
                }
            ],
            "Interval": 6000
        }
    ],
    "ByteOrder": 0,
    "ByteOrderFloats": true,
    "Active": true,
    "ReferenceCountStartsAtZero": true,
    "UseEnronMode": false,
    "Name": "WS100-1943",
    "Description": "",
    "ConnectionType": "TCP",
    "Profiles": {},
    "Requests": {
        "Interval": 6000
    },
    "Type": "Energy_Meter"
}
